# Generated by Django 4.2.3 on 2023-08-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('test_short_name', models.CharField(max_length=50)),
                ('test_price', models.IntegerField()),
            ],
        ),
    ]
