# Generated by Django 4.2.3 on 2023-08-12 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_sub_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_normal', models.CharField(max_length=50)),
                ('sub_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_sbu_test', to='tests.add_test')),
            ],
        ),
    ]
