# Generated by Django 4.2.3 on 2023-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_add_sub_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_sub_test',
            name='sub_part',
            field=models.IntegerField(),
        ),
    ]
