# Generated by Django 4.2.3 on 2023-08-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_add_sub_test_sub_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_sub_test',
            name='Test_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_sbu_test', to='tests.add_test'),
            preserve_default=False,
        ),
    ]
