# Generated by Django 4.2.3 on 2023-08-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_add_sub_test_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_sub_test',
            name='Test_name',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='add_sbu_test', to='tests.add_test'),
        ),
    ]
