# Generated by Django 4.2.4 on 2023-08-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_add_sub_test_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_normal', models.CharField(max_length=50)),
                ('sub_part', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Add_test',
            new_name='Test',
        ),
        migrations.DeleteModel(
            name='Add_sub_test',
        ),
        migrations.AddField(
            model_name='subtest',
            name='test_name',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='Test_name', to='tests.test'),
        ),
    ]
