# Generated by Django 4.2.4 on 2023-08-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_subtest_rename_add_test_test_delete_add_sub_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='sub_normal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='sub_part',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
