# Generated by Django 4.2.4 on 2023-08-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_subtest_sub_normal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_short_name',
        ),
    ]
