# Generated by Django 4.2.4 on 2023-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_test_test_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('p_age', models.IntegerField()),
                ('p_phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
