# Generated by Django 4.2.4 on 2023-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='sub_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='sub_normal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
