# Generated by Django 4.2.4 on 2023-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_alter_subtest_sub_name_alter_subtest_sub_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='sub_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtest',
            name='sub_normal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
