# Generated by Django 4.2.4 on 2023-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_alter_patient_p_age_alter_subtest_sub_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=50),
        ),
    ]
