# Generated by Django 4.2.4 on 2023-08-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_alter_patient_p_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_total', models.IntegerField(blank=True, null=True)),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('p_name', models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='p_check', to='tests.patient')),
                ('test_name', models.ManyToManyField(to='tests.test')),
            ],
        ),
    ]
