# Generated by Django 4.2.4 on 2023-08-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_alter_check_p_name_alter_patient_p_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-p_name']},
        ),
    ]
