# Generated by Django 4.2.4 on 2023-08-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_alter_check_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={},
        ),
    ]
