# Generated by Django 4.2.4 on 2023-08-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_alter_check_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Patient Name'),
        ),
    ]
