# Generated by Django 4.2.4 on 2023-08-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_alter_patient_p_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_result', models.CharField(max_length=50)),
                ('check_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.check')),
                ('sub_id', models.ManyToManyField(max_length=50, to='tests.subtest')),
            ],
        ),
    ]
