# Generated by Django 4.2.4 on 2023-08-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_alter_check_items_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='p_name',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_check', to='tests.patient'),
        ),
    ]
