# Generated by Django 4.2.4 on 2023-08-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_alter_subtest_sub_normal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_items',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='check_items',
            name='sub_id',
            field=models.ManyToManyField(to='tests.subtest'),
        ),
    ]
