# Generated by Django 4.2.4 on 2023-08-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_remove_check_items_sub_id_check_items_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_items',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='check_items',
            name='sub_id',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.subtest'),
        ),
    ]
