# Generated by Django 4.2.4 on 2023-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_remove_check_items_sub_id_check_items_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_items',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='check_items',
            name='sub_id',
            field=models.ManyToManyField(to='tests.subtest'),
        ),
    ]
