# Generated by Django 4.2.4 on 2023-08-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_remove_check_items_sub_id_check_items_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_items',
            name='sub_id',
        ),
    ]
