# Generated by Django 4.2.4 on 2023-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_b_v', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
