# Generated by Django 4.2.3 on 2023-08-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_category_job_vacancy_job_description_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_catogrey', to='job.category'),
            preserve_default=False,
        ),
    ]
