# Generated by Django 4.2.3 on 2023-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
